"""modelo inicial: usuario, autor, exposicion, sala, zona, obra

Revision ID: 618b523d69f8
Revises: 
Create Date: 2026-06-02 14:28:15.276916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618b523d69f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=160), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('contacto', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_autor_nombre'), ['nombre'], unique=False)

    op.create_table('exposicion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exposicion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exposicion_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_exposicion_slug'), ['slug'], unique=True)

    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_email'), ['email'], unique=True)

    op.create_table('sala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exposicion_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('plantilla_3d', sa.String(length=80), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exposicion_id'], ['exposicion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sala', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sala_exposicion_id'), ['exposicion_id'], unique=False)

    op.create_table('zona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sala_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('tipo_admitido', sa.String(length=20), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sala_id'], ['sala.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zona', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zona_sala_id'), ['sala_id'], unique=False)

    op.create_table('obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('zona_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('tecnica', sa.String(length=160), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('ancho_cm', sa.Float(), nullable=True),
    sa.Column('alto_cm', sa.Float(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True),
    sa.Column('cloudinary_url', sa.String(length=500), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['autor.id'], ),
    sa.ForeignKeyConstraint(['zona_id'], ['zona.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zona_id', 'orden', name='uq_obra_zona_orden')
    )
    with op.batch_alter_table('obra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obra_autor_id'), ['autor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_obra_zona_id'), ['zona_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obra_zona_id'))
        batch_op.drop_index(batch_op.f('ix_obra_autor_id'))

    op.drop_table('obra')
    with op.batch_alter_table('zona', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zona_sala_id'))

    op.drop_table('zona')
    with op.batch_alter_table('sala', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sala_exposicion_id'))

    op.drop_table('sala')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_email'))

    op.drop_table('usuario')
    with op.batch_alter_table('exposicion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exposicion_slug'))
        batch_op.drop_index(batch_op.f('ix_exposicion_estado'))

    op.drop_table('exposicion')
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_autor_nombre'))

    op.drop_table('autor')
    # ### end Alembic commands ###
